### ISSUE TITLE
[META] first release roadmap

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-input-snmp#2]
- The [`SNMP4J` OSS Java library](http://www.snmp4j.org/) was chosen for the plugin runtime SNMP support. The plugin is written in Ruby by calling/wrapping the library classes. SNMP4J has support for all protocols SNMPv1/v2c/v3. 

- The [`libsmi` OSS library](https://www.ibr.cs.tu-bs.de/projects/libsmi/) will be used for the **external** MIB files parsing support. Users will be able to *import* MIB files by installing libsmi on their platform and using the command line tool to import a MIB file for the plugin, with something like that:
```
smidump -k -f python path/to/some/original/mib > path/to/some/imported/mib.dic
```

No processing or computation is planned on the results. These will need to be done in downstream filters or at index/query time in ES/Kibana. 

## V1 Beta

See PR #1 

- [x] The plugin first iteration supportsthese options:
  - `get` on a configured list of OIDs to retrieve scalar values the these OIDs.
  - `walk` on a configured list of OIDs to retrieve the substree of information rooted at these OIDs.
  - `hosts` will specify a list of hosts addresses to perform the `get` and `walk` operations.
  - `interval` for the sleep interval between each poll cycle.
  - `mib path` to specify mib files for translating OID numbers to field names in the generated event.

- [x] Only **SNMPv2c** over **UDP** is supported.  
- [x] Simple threaded polling loop that cycles through all defined hosts to perform the get/walk operations. A single poll cycle including all get and walk results for a single host produces one event. 
- [x] Support MIB files to map the numeric OIDs to MIB field names in the resulting event. 

## V1 GA 

- [ ] Support both UDP and TCP transport
- [ ] Support SNMPv1
- [ ] Better error handling
- [ ] Fix code TODOs
- [ ] Add `lib/logstash/inputs/snmp.rb` tests/specs
- [ ] Add `lib/logstash/inputs/snmp/client.rb` tests/specs 
- [ ] Pre-package all MIBs included in `libsmi` into the plugin so these do not need to be *imported*

## Post V1 GA

- [ ] Support SNMPv3
- [ ] Polling thread pool
- [ ] Hosts auto-discovery
- [ ] Distributed execution. This should tie-in with the future distributed LS architecture. We can also explore other ideas such as decoupling the hosts discovery from the polling and have the former feed the latter. 
- [ ] Externally configured options such as hosts lists 
- [ ] Support SNMP traps

**Comment by colinsurprenant** [comment]
initial version `0.1.0.beta1` merged in master.

**Comment by colinsurprenant** [comment]
0.1.0.beta3 pushed which adds support for SNMPv1 and TCP. Also 0.1.0.beta2 added host field information in the event.

**Comment by dfdalamar** [comment]
Hi, is there support for SNMPv2?  I would love to start testing this.

**Comment by colinsurprenant** [comment]
@dfdalamar for now SNMPv1 and SNMPv2c are supported. Next in line is SNMPv3. Does SNMPv2c work for you?

**Comment by dfdalamar** [comment]
That is perfect!!!!

**Comment by colinsurprenant** [comment]
@dfdalamar looking forward for your feedback - do not hesitate to open bug/suggestion issues, I will followup as we are ramping up toward the 1.0 release soon.

**Comment by dfdalamar** [comment]
Please excuse my ignorance.  How do I install this?  Can I use the logstash plugin install command?

**Comment by colinsurprenant** [comment]
@dfdalamar since this is a beta version you have to explicitly specify the version like this:
```
$  bin/logstash-plugin install --version 0.1.0.beta3 logstash-input-snmp
```

**Comment by dfdalamar** [comment]
Thanks!!!!

**Comment by dfdalamar** [comment]
I have installed but cannot find the files to edit.  I have all kinds of MIBS on my machine, I am running rrd with another program.

**Comment by colinsurprenant** [comment]
@dfdalamar could you please open a new issue with your specific usage problems and we can followup in there? This is not relevant to this release roadmap meta issue here. Thank you. Also note that there are configuration examples [in the wiki](https://github.com/logstash-plugins/logstash-input-snmp/wiki) that might be useful.

**Comment by swtrux** [comment]
I am very interested in using this new plugin but need the SNMPv3 support.  I have not seen any progress lately in this tread.  Is this feature still coming?

**Comment by colinsurprenant** [comment]
I added initial support for SNMPv3 in #27 - once reviewed I will publish it in beta5.

**Comment by colinsurprenant** [comment]
**0.1.0.beta5** was just published and includes a number of bug fixes, support for SNMPv3 and the inclusion of all **ietf** MIBs. 

```
$ bin/logstash-plugin install --version 0.1.0.beta3 logstash-input-snmp
```

**Comment by colinsurprenant** [comment]
v1.1.0 with table support is out!
